site_name: OSG User School 2019
site_url: https://opensciencegrid.org/user-school-2019/
repo_name: null
repo_url: null
theme:
  name: windmill
  custom_dir: theme-customizations

extra:
  article_nav_top: false

extra_css:
  - css/extra.css
  - css/codehilite.css

# Suppress weird JavaScript problems with development server
extra_javascript: []

pages:
  - User School 2019:             index.md
  - Curriculum:
    - High-level overview:        curriculum/overview.md
  - Logistics:
    - General information:        logistics/index.md
    - Visa requirements:          logistics/personal-info.md
    - Travel planning:            logistics/travel.md
    - Hotel information:          logistics/hotel.md
    - Local transportation:       logistics/local-transportation.md
    - School location:            logistics/location.md
  - Materials:
    - Overview:                   materials/index.md
    - Monday Exercises:
      - Exercise 1.1:             materials/day1/part1-ex1-login.md
      - Exercise 1.2:             materials/day1/part1-ex2-commands.md
      - Exercise 1.3:             materials/day1/part1-ex3-jobs.md
      - Exercise 1.4:             materials/day1/part1-ex4-logs.md
      - Exercise 1.5:             materials/day1/part1-ex5-request.md
      - Exercise 1.6:             materials/day1/part1-ex6-remove.md
      - Bonus Exercise 1.7:       materials/day1/part1-ex7-compile.md
      - Exercise 2.1:             materials/day1/part2-ex1-files.md
      - Exercise 2.2:             materials/day1/part2-ex2-queue-n.md
      - Exercise 2.3:             materials/day1/part2-ex3-queue-matching.md
      - Exercise 2.4:             materials/day1/part2-ex4-queue-from.md
      - Exercise 3.1:             materials/day1/part3-ex1-queue.md
      - Exercise 3.2:             materials/day1/part3-ex2-status.md
      - Exercise 3.3:             materials/day1/part3-ex3-job-retry.md
      - Exercise 4.1:             materials/day1/part4-ex1-submit-refresher.md
      - Exercise 4.2:             materials/day1/part4-ex2-login-scp.md
      - Exercise 4.3:             materials/day1/part4-ex3-submit-osg.md
      - Exercise 4.4:             materials/day1/part4-ex4-hardware-diffs.md
      - Exercise 4.5:             materials/day1/part4-ex5-software-diffs.md
    - Thursday Exercises:
      - Exercise 1.1:             materials/day4/part1-ex1-data-needs.md
      - Exercise 1.2:             materials/day4/part1-ex2-file-transfer.md
      - Exercise 1.3:             materials/day4/part1-ex3-blast-split.md
      - Exercise 2.1:             materials/day4/part2-ex1-blast-proxy.md
      - Exercise 2.2:             materials/day4/part2-ex2-stashcache-shared.md
      - Exercise 2.3:             materials/day4/part2-ex3-stashcache-unique.md
      - Exercise 3.1:             materials/day4/part3-ex1-input.md
      - Exercise 3.1:             materials/day4/part3-ex2-output.md
      - Exercise 4.1:             materials/day4/part4-ex1-simple-dag.md
      - Exercise 4.2:             materials/day4/part4-ex2-mandelbrot.md
      - Exercise 4.3:             materials/day4/part4-ex3-complex-dag.md
      - Exercise 4.4:             materials/day4/part4-ex4-failed-dag.md
      - Bonus Exercises 4.5:      materials/day4/part4-ex5-challenges.md



markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - osg_markdown.colors
